global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    scrape_interval: 5s
    static_configs:
      # ★★★ 수정: 'app:8000' -> 'host.docker.internal:8000'
      - targets: ['host.docker.internal:8000']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']