# Cargo configuration to speed up builds and prevent hangs

[build]
# Use parallel compilation but limit to prevent hangs
jobs = 4

# Environment variables for llama.cpp compilation
[env]
# Disable CUDA compilation by default to speed up builds
LLAMA_CUDA = "OFF"
# Use faster compilation flags
CMAKE_BUILD_TYPE = "Release"
# Limit parallel jobs for llama.cpp to prevent hanging
CMAKE_BUILD_PARALLEL_LEVEL = "4"

# Custom commands for Shimmy development
[alias]
# Quick development tests
test-quick = [
    "test", "--lib", "--features", "huggingface"
]

# Build shortcuts  
build-all = [
    "build", "--all-features"
]

build-release = [
    "build", "--release", "--all-features"
]

# Quality commands
check-all = [
    "check", "--all-features"
]

fmt-check = [
    "fmt", "--", "--check"
]

lint = [
    "clippy", "--all-features", "--", "-D", "warnings"
]
